apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-ui
  labels:
    {{- include "chart.labels.ui" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels.ui" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-api
  labels:
    {{- include "chart.labels.api" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels.api" . | nindent 4 }}
---