export const Order = [
    'Configuracion General',
    'Pais',
    'Banco',
    'TipoCambio',
    'Canal',
    'ParticipanteIndirecto',
    'Catalogo',
    'Parametro',
    'Orquestación',
    'Configuración',
    'Consultas',
    'Consulta Transacciones',
    'Tabla',
    'PaisCanal',
    'Flujo',
    'DetalleFlujo',
    'MatrizEstado',
    'TransferenciaACH',
    'InformacionAdicional',
];
